"""Refactoring task table

Revision ID: 0275015f2fd1
Revises: f9a0676310ea
Create Date: 2023-10-23 01:11:13.988666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0275015f2fd1'
down_revision: Union[str, None] = 'f9a0676310ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('correct_option_id', sa.String(length=16), nullable=False))
    op.drop_column('tasks', 'correct_options_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('correct_options_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'correct_option_id')
    # ### end Alembic commands ###
