"""Start alembic

Revision ID: 379b9d292ce0
Revises: 
Create Date: 2023-10-20 00:34:12.706659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '379b9d292ce0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test_task')
    op.drop_table('File_to_prepare')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.BIGINT(), server_default=sa.text('nextval(\'"Users_user_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='Users_pkey'),
    sa.UniqueConstraint('username', name='Users_username_key')
    )
    op.create_table('File_to_prepare',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"File_to_prepare_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('type_file', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='File_to_prepare_pkey')
    )
    op.create_table('Test_task',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Test_task_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('task_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('picture_file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.ARRAY(sa.VARCHAR(length=16)), autoincrement=False, nullable=False),
    sa.Column('true_answer', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shipped', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Test_task_pkey')
    )
    # ### end Alembic commands ###
