"""add cascade

Revision ID: 4e49b6be8333
Revises: 99e796537f17
Create Date: 2023-10-27 21:41:09.967256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e49b6be8333'
down_revision: Union[str, None] = '99e796537f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'explanation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'explanation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
