"""Refactoring association table

Revision ID: aa0f11451203
Revises: 0275015f2fd1
Create Date: 2023-10-23 16:03:33.581661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0f11451203'
down_revision: Union[str, None] = '0275015f2fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_task_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'task_id'),
    sa.UniqueConstraint('user_id', 'task_id', name='idx_unique_user_task')
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='association_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='association_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='association_pkey')
    )
    op.drop_table('user_task_association')
    # ### end Alembic commands ###
