"""Rename collums of task table

Revision ID: f9a0676310ea
Revises: 379b9d292ce0
Create Date: 2023-10-22 20:43:47.554484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f9a0676310ea"
down_revision: Union[str, None] = "379b9d292ce0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.add_column("tasks", sa.Column("question", sa.String(), nullable=False))
    op.add_column(
        "tasks", sa.Column("correct_options_id", sa.String(length=16), nullable=False)
    )
    op.drop_column("tasks", "task_text")
    op.drop_column("tasks", "true_answer")
    op.create_unique_constraint(None, "users", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.add_column(
        "tasks",
        sa.Column(
            "true_answer", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tasks",
        sa.Column("task_text", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "correct_options_id")
    op.drop_column("tasks", "question")
    op.create_table(
        "task",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("task_text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("picture_file_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "options",
            postgresql.ARRAY(sa.VARCHAR(length=32)),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "true_answer", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
        sa.Column("explanation", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="task_pkey"),
    )
    # ### end Alembic commands ###
